name: Cypress Tests

on: 
  push:
    branches: main 
 
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
     - uses: actions/checkout@v3
     - name: Cypress.io
       uses: cypress-io/github-actions@v-2.9.7
       with:
         start: npm start
       
